// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYyzAqSeOjp4jLBet0zdT6ZDzySomzV80',
    appId: '1:548456755056:web:633d81d1d18b70b2f9a9b5',
    messagingSenderId: '548456755056',
    projectId: 'shubham-jewellers-1976',
    authDomain: 'shubham-jewellers-1976.firebaseapp.com',
    storageBucket: 'shubham-jewellers-1976.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoR4bdnNAFxCPFxwNj6sTSsU6sc2m5e6o',
    appId: '1:548456755056:android:9ee2b71afad4e753f9a9b5',
    messagingSenderId: '548456755056',
    projectId: 'shubham-jewellers-1976',
    storageBucket: 'shubham-jewellers-1976.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3lYTd0IkodH0n_COu1IwPeu5n5xiAiIc',
    appId: '1:548456755056:ios:e6ea90ce8183d2d1f9a9b5',
    messagingSenderId: '548456755056',
    projectId: 'shubham-jewellers-1976',
    storageBucket: 'shubham-jewellers-1976.firebasestorage.app',
    iosBundleId: 'com.example.weightCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3lYTd0IkodH0n_COu1IwPeu5n5xiAiIc',
    appId: '1:548456755056:ios:e6ea90ce8183d2d1f9a9b5',
    messagingSenderId: '548456755056',
    projectId: 'shubham-jewellers-1976',
    storageBucket: 'shubham-jewellers-1976.firebasestorage.app',
    iosBundleId: 'com.example.weightCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYyzAqSeOjp4jLBet0zdT6ZDzySomzV80',
    appId: '1:548456755056:web:a05ad1108681efb7f9a9b5',
    messagingSenderId: '548456755056',
    projectId: 'shubham-jewellers-1976',
    authDomain: 'shubham-jewellers-1976.firebaseapp.com',
    storageBucket: 'shubham-jewellers-1976.firebasestorage.app',
  );
}
